## Week 3: Matrix Multiplication

In [1]:
import numpy as np

In [2]:
A = np.array([[4, 9, 9], [9, 1, 6], [9, 2, 3]])
B = np.array([[2, 2], [5, 7], [4, 4]])

In [3]:
A @ B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [4]:
np.matmul(A, B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

Change the order of matrix might cause column-row mismatch

In [6]:
try:
    np.matmul(B, A)
except ValueError as err:
    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


For vectors (not matrices), vectors `x` are automatically transposed and the matrix multiplication of `x` and `y` gives the same result as `np.dot()`

In [7]:
x = np.array([1, -2, -5])
y = np.array([4, 3, -1])

In [8]:
np.matmul(x, y)

np.int64(3)

In [9]:
np.dot(x, y)

np.int64(3)

In [ ]:
np.dot(A, B) # also works with matrices multiplication (dot product version for matrices)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])