# Week 1. Systems of Linear Equations

## Numpy Basics

In [2]:
import numpy as np

Numpy has more (built in) functions and takes up less space and time than Python list (array), because of its extensive API integration.

In [3]:
# Array object in numpy is ndarray (n-dimensional array)
one_dimensional_array = np.array([10,12])
one_dimensional_array

array([10, 12])

## Create an array 

In [4]:
## 1-D
x1 = np.array([1,2])
print(x1)
## 2-D 
x11 = np.array([[1, 2, 3], [4, 5, 6]])
print(x11)

## Array of evenly spaced values within a given interval 
x2 = np.arange(5)
print(x2)
x3 = np.arange(0, 5, 0.5)
print(x3)
x6 = np.arange(0, 5, 0.5, dtype=int)
print(x6)

## Array of N evenly spaced values within a given interval (linearly spaced array)
x4 = np.linspace(0, 5, 10)
print(x4) # default type: float
x5 = np.linspace(0, 5, 10, dtype=int)
print(x5) # rounded to the closest integer

## Array of N 1s
x7 = np.ones(5)
print(x7)

## Array of N 0s
x8 = np.zeros(5)
print(x8)

## Array of shape N, emtpy
x9 = np.empty(5)
print(x9)

## Array of shape N with random numbers between 0 and 1
x10 = np.random.rand(5)
print(x10)


[1 2]
[[1 2 3]
 [4 5 6]]
[0 1 2 3 4]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 0 0 0 0 0 0 0 0 0]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[0 0 1 1 2 2 3 3 4 5]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0.85473259 0.46661644 0.49577919 0.53843444 0.78436462]


## Size, shape, dimension

In [16]:
## Reshape
x1 = np.array([1, 2, 3, 4, 5, 6]) 
x2 = np.reshape(x1, (2,3)) #([[1x3],[1x3]])
print(x2)


[[1 2 3]
 [4 5 6]]


In [17]:
## Shape
x2.shape

(2, 3)

In [18]:
## Dimension
x2.ndim

2

In [19]:
## Size
x2.size

6

## Operations
### Broadcast

In [20]:
x1 * 1.5

array([1.5, 3. , 4.5, 6. , 7.5, 9. ])

## Indexing & Slicing

In [22]:
x1[:] == x1[::]

array([ True,  True,  True,  True,  True,  True])

In [26]:
# Full, Column 0 of all rows, Row 0 of all columns
x2[:, :], x2[:, 0], x2[0, :]

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 4]),
 array([1, 2, 3]))

In [32]:
# Last 2 rows (only 1 here though)
print(x2[1:3])
print(x2[1:3,:]) # same with ,:

# Last 2 columns
print(x2[:, 1: 3]) # need :,

[[4 5 6]]
[[4 5 6]]
[[2 3]
 [5 6]]


## Stacking
To join 2 or more arrays horizontally or vertically (done along a new axis)
- `np.vstack()` - stacks vertically
- `np.hstack()` - stacks horizontally
- `np.hsplit()` - splits an array into several smaller arrays

In [37]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

## Stack vertically: np.vstack( (a1, a2,...) )
print(np.vstack((a1, a2))) 

## Stack horizontally
print(np.hstack((a1, a2)))


[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


## Exercise 
Is there a difference between `np.zeros()` and `np.empty()`? Select one of the options given:
- A. No difference, they both output arrays of zeros. 
- B. `np.zeros()` is not initialized, but gives an output of zeros. 
- C. `np.zeros()` is faster to execute than `np.empty()`.
- D. `np.empty()` outputs an uninitialized array, but `np.zeros()` outputs an initialized array of value zero.

D. np.empty() creates an array with unitialized elements from available memory space and may be faster to execute.