# Week 1. Systems of Linear Equations
## Represent systems of linear equations as matrices

In [2]:
import numpy as np
import matplotlib.pyplot as plt
#from utils import plot_lines

$$
\begin{cases} 
-x_1+3x_2=7, \\ 3x_1+2x_2=1, \end{cases}\tag{1}
$$

In [5]:
A = np.array([[-1, 3], [3, 2]], dtype=float)
b = np.array([7, 1])
A, b

(array([[-1.,  3.],
        [ 3.,  2.]]),
 array([7, 1]))

To find solution of the linear equation system, we use `np.linalg.solve(A, b)`

In [6]:
np.linalg.solve(A, b)

array([-1.,  2.])

To find determinant, use `np.linalg.det(A)`

In [19]:
np.linalg.det(A) # non-zero determinant --> non-singular system with 1 unique solution

np.float64(-11.000000000000002)

## Visualize

In [20]:
A_system = np.hstack((A, b.reshape((2, 1))))
A_system

array([[-1.,  3.,  7.],
       [ 3.,  2.,  1.]])

In [22]:
#plot.lines(A_system)

## Singular

### No Solution
$$
\begin{cases} 
-x_1+3x_2=7, \\ 3x_1-9x_2=1, \end{cases}\tag{2}
$$

In [24]:
A = np.array([[-1, 3], [3, -9]])
b = np.array([7, 1])
np.linalg.det(A)

np.float64(-4.996003610813175e-16)

In [26]:
try:
    x = np.linalg.solve(A, b)
except np.linalg.LinAlgError as err:
    print(err)

Singular matrix


### Infinite Number of Solutions
$$
\begin{cases} 
-x_1+3x_2=7, \\ 3x_1-9x_2=-21, \end{cases}\tag{3}
$$

In [27]:
b = np.array([7, -21])